# Generated by Django 4.2.5 on 2023-10-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название точки')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название команды')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(verbose_name='Время прибытия на точку')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала квеста на точке')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.point')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team')),
            ],
        ),
    ]
