# Generated by Django 4.2.6 on 2023-10-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='start_time',
        ),
        migrations.AddField(
            model_name='stat',
            name='type',
            field=models.IntegerField(choices=[(1, 'Прибытие на точку'), (2, 'Старт квеста'), (3, 'Финиш команды')], default=1, verbose_name='Действие'),
        ),
    ]
