# Generated by Django 4.2.6 on 2023-10-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_stat_arrival_time_remove_stat_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время действия'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.IntegerField(choices=[(1, 'Прибытие команды на точку'), (2, 'Старт квеста командой'), (3, 'Финиш команды')], default=1, verbose_name='Действие'),
        ),
    ]
