# Generated by Django 4.2.6 on 2023-10-13 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stat_time_alter_stat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 23, 35, 17, 23911), verbose_name='Время действия'),
        ),
    ]
