# Generated by Django 4.2.6 on 2023-10-13 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 23, 57, 59, 66348), verbose_name='Время действия'),
        ),
    ]
