# Generated by Django 4.2.6 on 2023-10-13 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_stat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 0, 10, 24, 924521), verbose_name='Время действия'),
        ),
    ]
