# Generated by Django 5.0 on 2023-12-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_stat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.ManyToManyField(to='main.point'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время действия'),
        ),
    ]
