# Generated by Django 5.0 on 2023-12-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_team_points_alter_stat_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.CreateModel(
            name='TeamPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер точки назначения команды')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.point')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team')),
            ],
        ),
    ]
