# Generated by Django 5.0 on 2023-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_team_points_teampoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'verbose_name': 'Запись статистики', 'verbose_name_plural': 'Записи статистики'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='teampoints',
            options={'verbose_name': 'Точка команды', 'verbose_name_plural': 'Точки команд'},
        ),
        migrations.AlterField(
            model_name='teampoints',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер точки назначения команды'),
        ),
    ]
